USE [ADSReports]
GO

/****** Object:  Table [dbo].[tbl_CbPruebas_OTPDEFCAP]    Script Date: 26/03/2020 7:33:31 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_CbPruebas_OTPDEFCAP](
	[O_WorkItemSK] [int] NULL,
	[O_Id] [int] NULL,
	[O_Titulo] [nvarchar](256) NULL,
	[O_Estado] [nvarchar](256) NULL,
	[O_Disciplina] [nvarchar](256) NULL,
	[O_FechaCierre] [datetime] NULL,
	[P_WorkItemSK] [int] NULL,
	[P_Id] [int] NULL,
	[P_Titulo] [nvarchar](256) NULL,
	[P_Estado] [nvarchar](256) NULL,
	[P_ModificadoPor] [nvarchar](256) NULL,
	[P_FechaModificacion] [datetime] NULL,
	[P_Motivo] [nvarchar](256) NULL,
	[P_AsignadoA] [nvarchar](256) NULL,
	[P_CreadoPor] [nvarchar](256) NULL,
	[P_FechaCreacion] [datetime] NULL,
	[P_Sistema] [nvarchar](256) NULL,
	[P_TipoPrueba] [nvarchar](256) NULL,
	[P_NivelPrueba] [nvarchar](256) NULL,
	[P_TipoServicioPrueba] [nvarchar](256) NULL,
	[P_TipoValidacion] [nvarchar](256) NULL,
	[P_GerenciaSolicitanteUAT] [nvarchar](256) NULL,
	[P_LiderSoporte] [nvarchar](256) NULL,
	[P_NumeroCelularSoporte] [nvarchar](256) NULL,
	[P_FechaInicialDespliegue] [datetime] NULL,
	[P_FechaFinalDespliegue] [datetime] NULL,
	[P_FechaPlaneadaInicialUAT] [datetime] NULL,
	[P_FechaPlaneadaFinalUAT] [datetime] NULL,
	[P_TiempoContingencia] [nvarchar](256) NULL,
	[P_FechaRealInicioUAT] [datetime] NULL,
	[P_FechaRealFinUAT] [datetime] NULL,
	[P_GestorUAT] [nvarchar](256) NULL,
	[P_NumeroCelularGestor] [nvarchar](256) NULL,
	[P_FechaEsperadaFinPrueba] [datetime] NULL,
	[P_FechaSmokeTest] [datetime] NULL,
	[P_SolicitadoFecha] [datetime] NULL,
	[P_AmbientePruebas] [nvarchar](256) NULL,
	[P_AnunciadaEntregada] [nvarchar](256) NULL,
	[P_Bloqueado] [nvarchar](256) NULL,
	[P_Subsidiaria] [nvarchar](256) NULL,
	[P_Garantia] [nvarchar](256) NULL,
	[P_NivelComplejidad] [nvarchar](256) NULL,
	[DEF_WorkItemSK] [int] NULL,
	[DEF_Id] [int] NULL,
	[DEF_Estado] [nvarchar](256) NULL,
	[DEF_Titulo] [nvarchar](256) NULL,
	[DEF_ModificadoPor] [nvarchar](256) NULL,
	[DEF_Motivo] [nvarchar](256) NULL,
	[DEF_motivoResolucion] [nvarchar](256) NULL,
	[DEF_AsignadoA] [nvarchar](256) NULL,
	[DEF_CreadoPor] [nvarchar](256) NULL,
	[DEF_FechaCreacion] [datetime] NULL,
	[DEF_Prioridad] [int] NULL,
	[DEF_Gravedad] [nvarchar](256) NULL,
	[DEF_Evaluacion] [nvarchar](256) NULL,
	[DEF_Bloqueado] [nvarchar](256) NULL,
	[DEF_UsuarioReporta] [nvarchar](256) NULL,
	[DEF_AreaNegocio] [nvarchar](256) NULL,
	[DEF_IM] [int] NULL,
	[DEF_Disciplina] [nvarchar](256) NULL,
	[DEF_CausaPrincipal] [nvarchar](256) NULL,
	[DEF_Causal] [nvarchar](256) NULL,
	[DEF_AtribuibleA] [nvarchar](256) NULL,
	[DEF_EstimOriginal] [float] NULL,
	[DEF_TrabajoRestante] [float] NULL,
	[DEF_TrabajoCompletado] [float] NULL,
	[DEF_ComoSeEncontro] [nvarchar](256) NULL,
	[DEF_EncontradoEnEntorno] [nvarchar](256) NULL,
	[DEF_EncontradoEn] [nvarchar](256) NULL,
	[DEF_IntegradoEn] [nvarchar](256) NULL,
	[CAP_WorkItemSK] [int] NULL,
	[CAP_Id] [int] NULL,
	[CAP_Titulo] [nvarchar](256) NULL,
	[CAP_Estado] [nvarchar](256) NULL,
	[CAP_ModificadoPor] [nvarchar](256) NULL,
	[CAP_Motivo] [nvarchar](256) NULL,
	[CAP_AsignadoA] [nvarchar](256) NULL,
	[CAP_CreadoPor] [nvarchar](256) NULL,
	[CAP_FechaCreacion] [datetime] NULL,
	[CAP_Prioridad] [int] NULL,
	[CAP_EstadoAutomatizacion] [nvarchar](256) NULL,
	[CAP_Planeado] [nvarchar](256) NULL,
	[CAP_EsTestStandar] [nvarchar](256) NULL,
	[P_Fecha_Plan_Fin] [datetime] NULL
) ON [PRIMARY]

GO


