
  CREATE TABLE SALES.AJM_DOCUMENTOS 
   (	ID NUMBER(15,0) NOT NULL ENABLE, 
	ARCHIVO VARCHAR2(150 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	FECHA_CREACION TIMESTAMP (6) DEFAULT NULL NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT NULL NOT NULL ENABLE, 
	 CONSTRAINT AJM_DOCUMENTOS_PK PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;

   COMMENT ON COLUMN SALES.AJM_DOCUMENTOS.ID IS 'Llave primaria de la tabla autoincremental';
   COMMENT ON COLUMN SALES.AJM_DOCUMENTOS.ARCHIVO IS 'Nombre del archivo con la siguiente estructura (OUT_MADJUST_BATCH_ + timestamp [ddmmaaaahh24mmss])';
   COMMENT ON COLUMN SALES.AJM_DOCUMENTOS.FECHA_CREACION IS 'Fecha de creación del registro';
   COMMENT ON COLUMN SALES.AJM_DOCUMENTOS.ESTADO IS 'Estado del documento, (1) si el archivo ya fue procesado y (0) si el archivo no ha sido procesado';

  CREATE OR REPLACE EDITIONABLE TRIGGER SALES.ID_AJM_DOCUMENTOS_AUTO 
BEFORE INSERT ON SALES.AJM_DOCUMENTOS FOR EACH ROW
BEGIN
    IF NEW.ID IS NULL THEN
        SELECT ID_AJM_DOCUMENTOS_SEQ.NEXTVAL INTO NEW.ID FROM DUAL;
    END IF;
END;


ALTER TRIGGER SALES.ID_AJM_DOCUMENTOS_AUTO ENABLE;

